GRANT SELECT ON dbo.GARANTIAS_REALES_X_OPERACION_VW TO RAP_Garantias
GRANT SELECT ON dbo.GARANTIAS_VALOR_X_OPERACION_VW TO RAP_Garantias
GRANT SELECT ON dbo.VALUACIONES_GARANTIAS_REALES_SICC_VW TO RAP_Garantias
GRANT SELECT ON dbo.VALUACIONES_GARANTIAS_REALES_VW TO RAP_Garantias
GRANT SELECT ON dbo.vwmigbonosvalesprendas TO RAP_Garantias
GRANT SELECT ON dbo.vwmiggarantiafiduciara TO RAP_Garantias
GRANT SELECT ON dbo.vwmiggarantiareal TO RAP_Garantias
GRANT SELECT ON dbo.vwmiggarantiarealcontrol TO RAP_Garantias
GRANT SELECT ON dbo.vwmiggarantiarealduplicada TO RAP_Garantias
GRANT SELECT ON dbo.vwmiggarbin TO RAP_Garantias
GRANT SELECT ON dbo.vwmiggardeudorcodeudor TO RAP_Garantias
GRANT SELECT ON dbo.vwmiggargarantia TO RAP_Garantias
GRANT SELECT ON dbo.vwmiggargarantiasrelacionadasfidu TO RAP_Garantias
GRANT SELECT ON dbo.vwmiggargarantiasrelacionadasreales TO RAP_Garantias
GRANT SELECT ON dbo.vwmiggaroperacion TO RAP_Garantias
GRANT SELECT ON dbo.vwmiggaroperacionesactivas TO RAP_Garantias
GRANT SELECT ON dbo.vwmiggaroperaciongarantia TO RAP_Garantias
GRANT SELECT ON dbo.vwmiggaroperacionresumen TO RAP_Garantias
GRANT SELECT ON dbo.vwmiggartarjetas TO RAP_Garantias
GRANT SELECT ON dbo.vwmiggarvaluacionesreales TO RAP_Garantias