USE [GARANTIAS]
GO

IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'RAP_AccesoIntegracion' AND type = 'R')
CREATE ROLE [RAP_AccesoIntegracion] AUTHORIZATION [dbo]
GO


GRANT SELECT, INSERT, UPDATE ON dbo.GAR_GARANTIA_FIDUCIARIA TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, UPDATE ON dbo.GAR_GARANTIA_REAL TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, UPDATE ON dbo.GAR_GARANTIA_VALOR TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, UPDATE ON dbo.GAR_DEUDOR TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, UPDATE ON dbo.GAR_OPERACION TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, UPDATE ON dbo.GAR_VALUACIONES_REALES TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, UPDATE ON dbo.GAR_GARANTIAS_VALOR_X_OPERACION TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, UPDATE ON dbo.GAR_GARANTIAS_REALES_X_OPERACION TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, UPDATE ON dbo.GAR_GARANTIAS_FIDUCIARIAS_X_OPERACION TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, UPDATE ON dbo.GAR_SICC_BSMPC TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, UPDATE ON dbo.GAR_SICC_BSMCL TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, UPDATE ON dbo.GAR_SICC_PRMOC TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, UPDATE ON dbo.GAR_SICC_PRMGT TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, UPDATE ON dbo.GAR_SICC_PRHCS TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, UPDATE ON dbo.GAR_SICC_PRMCA TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, UPDATE ON dbo.GAR_SICC_PRMRI TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, UPDATE ON dbo.GAR_SICC_DAMHT TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, UPDATE ON dbo.GAR_SICC_PRMSC TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, UPDATE ON dbo.GAR_POLIZAS TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, UPDATE ON dbo.GAR_POLIZAS_RELACIONADAS TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, UPDATE ON dbo.TMP_POLIZAS TO RAP_AccesoIntegracion
GO

GRANT SELECT, INSERT  ON dbo.GAR_EJECUCION_PROCESO TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT ON dbo.GAR_EJECUCION_PROCESO_DETALLE TO RAP_AccesoIntegracion
GO

GRANT EXECUTE ON dbo.pa_RegistroEjecucionProceso TO RAP_AccesoIntegracion
GO
GRANT EXECUTE ON dbo.Eliminar_Datos_Estructuras_SICC TO RAP_AccesoIntegracion
GO
GRANT EXECUTE ON dbo.Migrar_Garantias_Sicc TO RAP_AccesoIntegracion
GO
GRANT EXECUTE ON dbo.Actualizar_Registros_Garantias_Sicc TO RAP_AccesoIntegracion
GO
GRANT EXECUTE ON dbo.Cargar_Contratos_Vencidos_Sicc TO RAP_AccesoIntegracion
GO
GRANT EXECUTE ON dbo.Obtener_Resultado_Ejecucion_Procesos_Replica TO RAP_AccesoIntegracion
GO
GRANT EXECUTE ON dbo.Replicar_Valuaciones_Reales_Sicc TO RAP_AccesoIntegracion
GO
GRANT EXECUTE ON dbo.Replicar_Datos_Garantias_Reales_Sicc TO RAP_AccesoIntegracion
GO
GRANT EXECUTE ON dbo.Procesar_Polizas_Migradas TO RAP_AccesoIntegracion
GO

GRANT SELECT, INSERT, UPDATE ON dbo.TMP_SAP_VWSGRPOLIZA TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, UPDATE ON dbo.TMP_SAP_VWSGRPOLIZACREDITOBANCARIO TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, UPDATE ON dbo.TMP_SAP_VWSGRPOLIZACONTRATOCREDITO TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, UPDATE ON dbo.TMP_SAP_POLIZASEXTERNAS TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, UPDATE ON dbo.TMP_SAP_VWSGRPOLIZAAUTO TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, UPDATE ON dbo.TMP_SAP_SGRPOLIZAOTRO TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, UPDATE ON dbo.TMP_SAP_SGRPOLIZAPATRIMONIAL TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, UPDATE ON dbo.TMP_SAP_VWSGRCONTRATOCREDITO TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, UPDATE ON dbo.TMP_SAP_VWSGRCREDITOBANCARIO TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, UPDATE ON dbo.TMP_GIROS_CONTRATOS TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, UPDATE ON dbo.GAR_COBERTURAS TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, UPDATE ON dbo.GAR_COBERTURAS_POLIZAS TO RAP_Garantias
GO
GRANT SELECT, INSERT, UPDATE ON dbo.TMP_SAP_COBERTURAS_POLIZAS TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, UPDATE ON dbo.TMP_SAP_SGRCOBERTURAS TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, UPDATE ON dbo.TMP_SAP_SGRTIPOS_POLIZA TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SAP_VWSGRPOLIZA_HST TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SAP_VWSGRPOLIZACREDITOBANCARIO_HST TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SAP_VWSGRPOLIZACONTRATOCREDITO_HST TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SAP_POLIZASEXTERNAS_HST TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SAP_VWSGRPOLIZAAUTO_HST TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SAP_SGRPOLIZAOTRO_HST TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SAP_SGRPOLIZAPATRIMONIAL_HST TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SAP_VWSGRCONTRATOCREDITO_HST TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SAP_VWSGRCREDITOBANCARIO_HST TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.POLIZAS_HST TO RAP_AccesoIntegracion
GO

