//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Negocios.BCR.MQ.Servicios {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSMQSoap", Namespace="http://tempuri.org/WSMQ/WSMQ")]
    public partial class WSMQ : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback MQSistarOperationCompleted;
        
        private System.Threading.SendOrPostCallback MQPrestOperationCompleted;
        
        private System.Threading.SendOrPostCallback MQTarjetasOperationCompleted;
        
        private System.Threading.SendOrPostCallback MQLOGONOperationCompleted;
        
        private System.Threading.SendOrPostCallback MQCDPSOperationCompleted;
        
        private System.Threading.SendOrPostCallback MQSICC00OperationCompleted;
        
        private System.Threading.SendOrPostCallback MQTASACIONOperationCompleted;
        
        private System.Threading.SendOrPostCallback MQPJOperationCompleted;
        
        private System.Threading.SendOrPostCallback MQMarchamosOperationCompleted;
        
        private System.Threading.SendOrPostCallback MQConectividadesOperationCompleted;
        
        private System.Threading.SendOrPostCallback MQSociedadesOperationCompleted;
        
        private System.Threading.SendOrPostCallback MQHistoricoOperationCompleted;
        
        private System.Threading.SendOrPostCallback MQPAFOperationCompleted;
        
        private System.Threading.SendOrPostCallback BUSMQSICC00OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSMQ() {
            this.Url = global::Negocios.Properties.Settings.Default.Negocios_BCR_MQ_Servicios_WSMQ;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event MQSistarCompletedEventHandler MQSistarCompleted;
        
        /// <remarks/>
        public event MQPrestCompletedEventHandler MQPrestCompleted;
        
        /// <remarks/>
        public event MQTarjetasCompletedEventHandler MQTarjetasCompleted;
        
        /// <remarks/>
        public event MQLOGONCompletedEventHandler MQLOGONCompleted;
        
        /// <remarks/>
        public event MQCDPSCompletedEventHandler MQCDPSCompleted;
        
        /// <remarks/>
        public event MQSICC00CompletedEventHandler MQSICC00Completed;
        
        /// <remarks/>
        public event MQTASACIONCompletedEventHandler MQTASACIONCompleted;
        
        /// <remarks/>
        public event MQPJCompletedEventHandler MQPJCompleted;
        
        /// <remarks/>
        public event MQMarchamosCompletedEventHandler MQMarchamosCompleted;
        
        /// <remarks/>
        public event MQConectividadesCompletedEventHandler MQConectividadesCompleted;
        
        /// <remarks/>
        public event MQSociedadesCompletedEventHandler MQSociedadesCompleted;
        
        /// <remarks/>
        public event MQHistoricoCompletedEventHandler MQHistoricoCompleted;
        
        /// <remarks/>
        public event MQPAFCompletedEventHandler MQPAFCompleted;
        
        /// <remarks/>
        public event BUSMQSICC00CompletedEventHandler BUSMQSICC00Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSMQ/WSMQ/MQSistar", RequestNamespace="http://tempuri.org/WSMQ/WSMQ", ResponseNamespace="http://tempuri.org/WSMQ/WSMQ", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MQSistar(string Mensaje) {
            object[] results = this.Invoke("MQSistar", new object[] {
                        Mensaje});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MQSistarAsync(string Mensaje) {
            this.MQSistarAsync(Mensaje, null);
        }
        
        /// <remarks/>
        public void MQSistarAsync(string Mensaje, object userState) {
            if ((this.MQSistarOperationCompleted == null)) {
                this.MQSistarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMQSistarOperationCompleted);
            }
            this.InvokeAsync("MQSistar", new object[] {
                        Mensaje}, this.MQSistarOperationCompleted, userState);
        }
        
        private void OnMQSistarOperationCompleted(object arg) {
            if ((this.MQSistarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MQSistarCompleted(this, new MQSistarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSMQ/WSMQ/MQPrest", RequestNamespace="http://tempuri.org/WSMQ/WSMQ", ResponseNamespace="http://tempuri.org/WSMQ/WSMQ", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MQPrest(string Mensaje) {
            object[] results = this.Invoke("MQPrest", new object[] {
                        Mensaje});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MQPrestAsync(string Mensaje) {
            this.MQPrestAsync(Mensaje, null);
        }
        
        /// <remarks/>
        public void MQPrestAsync(string Mensaje, object userState) {
            if ((this.MQPrestOperationCompleted == null)) {
                this.MQPrestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMQPrestOperationCompleted);
            }
            this.InvokeAsync("MQPrest", new object[] {
                        Mensaje}, this.MQPrestOperationCompleted, userState);
        }
        
        private void OnMQPrestOperationCompleted(object arg) {
            if ((this.MQPrestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MQPrestCompleted(this, new MQPrestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSMQ/WSMQ/MQTarjetas", RequestNamespace="http://tempuri.org/WSMQ/WSMQ", ResponseNamespace="http://tempuri.org/WSMQ/WSMQ", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MQTarjetas(string Mensaje) {
            object[] results = this.Invoke("MQTarjetas", new object[] {
                        Mensaje});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MQTarjetasAsync(string Mensaje) {
            this.MQTarjetasAsync(Mensaje, null);
        }
        
        /// <remarks/>
        public void MQTarjetasAsync(string Mensaje, object userState) {
            if ((this.MQTarjetasOperationCompleted == null)) {
                this.MQTarjetasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMQTarjetasOperationCompleted);
            }
            this.InvokeAsync("MQTarjetas", new object[] {
                        Mensaje}, this.MQTarjetasOperationCompleted, userState);
        }
        
        private void OnMQTarjetasOperationCompleted(object arg) {
            if ((this.MQTarjetasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MQTarjetasCompleted(this, new MQTarjetasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSMQ/WSMQ/MQLOGON", RequestNamespace="http://tempuri.org/WSMQ/WSMQ", ResponseNamespace="http://tempuri.org/WSMQ/WSMQ", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MQLOGON(string Mensaje) {
            object[] results = this.Invoke("MQLOGON", new object[] {
                        Mensaje});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MQLOGONAsync(string Mensaje) {
            this.MQLOGONAsync(Mensaje, null);
        }
        
        /// <remarks/>
        public void MQLOGONAsync(string Mensaje, object userState) {
            if ((this.MQLOGONOperationCompleted == null)) {
                this.MQLOGONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMQLOGONOperationCompleted);
            }
            this.InvokeAsync("MQLOGON", new object[] {
                        Mensaje}, this.MQLOGONOperationCompleted, userState);
        }
        
        private void OnMQLOGONOperationCompleted(object arg) {
            if ((this.MQLOGONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MQLOGONCompleted(this, new MQLOGONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSMQ/WSMQ/MQCDPS", RequestNamespace="http://tempuri.org/WSMQ/WSMQ", ResponseNamespace="http://tempuri.org/WSMQ/WSMQ", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MQCDPS(string Mensaje) {
            object[] results = this.Invoke("MQCDPS", new object[] {
                        Mensaje});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MQCDPSAsync(string Mensaje) {
            this.MQCDPSAsync(Mensaje, null);
        }
        
        /// <remarks/>
        public void MQCDPSAsync(string Mensaje, object userState) {
            if ((this.MQCDPSOperationCompleted == null)) {
                this.MQCDPSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMQCDPSOperationCompleted);
            }
            this.InvokeAsync("MQCDPS", new object[] {
                        Mensaje}, this.MQCDPSOperationCompleted, userState);
        }
        
        private void OnMQCDPSOperationCompleted(object arg) {
            if ((this.MQCDPSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MQCDPSCompleted(this, new MQCDPSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSMQ/WSMQ/MQSICC00", RequestNamespace="http://tempuri.org/WSMQ/WSMQ", ResponseNamespace="http://tempuri.org/WSMQ/WSMQ", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MQSICC00(string Mensaje) {
            object[] results = this.Invoke("MQSICC00", new object[] {
                        Mensaje});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MQSICC00Async(string Mensaje) {
            this.MQSICC00Async(Mensaje, null);
        }
        
        /// <remarks/>
        public void MQSICC00Async(string Mensaje, object userState) {
            if ((this.MQSICC00OperationCompleted == null)) {
                this.MQSICC00OperationCompleted = new System.Threading.SendOrPostCallback(this.OnMQSICC00OperationCompleted);
            }
            this.InvokeAsync("MQSICC00", new object[] {
                        Mensaje}, this.MQSICC00OperationCompleted, userState);
        }
        
        private void OnMQSICC00OperationCompleted(object arg) {
            if ((this.MQSICC00Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MQSICC00Completed(this, new MQSICC00CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSMQ/WSMQ/MQTASACION", RequestNamespace="http://tempuri.org/WSMQ/WSMQ", ResponseNamespace="http://tempuri.org/WSMQ/WSMQ", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MQTASACION(string Mensaje) {
            object[] results = this.Invoke("MQTASACION", new object[] {
                        Mensaje});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MQTASACIONAsync(string Mensaje) {
            this.MQTASACIONAsync(Mensaje, null);
        }
        
        /// <remarks/>
        public void MQTASACIONAsync(string Mensaje, object userState) {
            if ((this.MQTASACIONOperationCompleted == null)) {
                this.MQTASACIONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMQTASACIONOperationCompleted);
            }
            this.InvokeAsync("MQTASACION", new object[] {
                        Mensaje}, this.MQTASACIONOperationCompleted, userState);
        }
        
        private void OnMQTASACIONOperationCompleted(object arg) {
            if ((this.MQTASACIONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MQTASACIONCompleted(this, new MQTASACIONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSMQ/WSMQ/MQPJ", RequestNamespace="http://tempuri.org/WSMQ/WSMQ", ResponseNamespace="http://tempuri.org/WSMQ/WSMQ", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MQPJ(string Mensaje) {
            object[] results = this.Invoke("MQPJ", new object[] {
                        Mensaje});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MQPJAsync(string Mensaje) {
            this.MQPJAsync(Mensaje, null);
        }
        
        /// <remarks/>
        public void MQPJAsync(string Mensaje, object userState) {
            if ((this.MQPJOperationCompleted == null)) {
                this.MQPJOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMQPJOperationCompleted);
            }
            this.InvokeAsync("MQPJ", new object[] {
                        Mensaje}, this.MQPJOperationCompleted, userState);
        }
        
        private void OnMQPJOperationCompleted(object arg) {
            if ((this.MQPJCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MQPJCompleted(this, new MQPJCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSMQ/WSMQ/MQMarchamos", RequestNamespace="http://tempuri.org/WSMQ/WSMQ", ResponseNamespace="http://tempuri.org/WSMQ/WSMQ", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MQMarchamos(string Mensaje) {
            object[] results = this.Invoke("MQMarchamos", new object[] {
                        Mensaje});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MQMarchamosAsync(string Mensaje) {
            this.MQMarchamosAsync(Mensaje, null);
        }
        
        /// <remarks/>
        public void MQMarchamosAsync(string Mensaje, object userState) {
            if ((this.MQMarchamosOperationCompleted == null)) {
                this.MQMarchamosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMQMarchamosOperationCompleted);
            }
            this.InvokeAsync("MQMarchamos", new object[] {
                        Mensaje}, this.MQMarchamosOperationCompleted, userState);
        }
        
        private void OnMQMarchamosOperationCompleted(object arg) {
            if ((this.MQMarchamosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MQMarchamosCompleted(this, new MQMarchamosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSMQ/WSMQ/MQConectividades", RequestNamespace="http://tempuri.org/WSMQ/WSMQ", ResponseNamespace="http://tempuri.org/WSMQ/WSMQ", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MQConectividades(string Mensaje) {
            object[] results = this.Invoke("MQConectividades", new object[] {
                        Mensaje});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MQConectividadesAsync(string Mensaje) {
            this.MQConectividadesAsync(Mensaje, null);
        }
        
        /// <remarks/>
        public void MQConectividadesAsync(string Mensaje, object userState) {
            if ((this.MQConectividadesOperationCompleted == null)) {
                this.MQConectividadesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMQConectividadesOperationCompleted);
            }
            this.InvokeAsync("MQConectividades", new object[] {
                        Mensaje}, this.MQConectividadesOperationCompleted, userState);
        }
        
        private void OnMQConectividadesOperationCompleted(object arg) {
            if ((this.MQConectividadesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MQConectividadesCompleted(this, new MQConectividadesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSMQ/WSMQ/MQSociedades", RequestNamespace="http://tempuri.org/WSMQ/WSMQ", ResponseNamespace="http://tempuri.org/WSMQ/WSMQ", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MQSociedades(string Mensaje) {
            object[] results = this.Invoke("MQSociedades", new object[] {
                        Mensaje});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MQSociedadesAsync(string Mensaje) {
            this.MQSociedadesAsync(Mensaje, null);
        }
        
        /// <remarks/>
        public void MQSociedadesAsync(string Mensaje, object userState) {
            if ((this.MQSociedadesOperationCompleted == null)) {
                this.MQSociedadesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMQSociedadesOperationCompleted);
            }
            this.InvokeAsync("MQSociedades", new object[] {
                        Mensaje}, this.MQSociedadesOperationCompleted, userState);
        }
        
        private void OnMQSociedadesOperationCompleted(object arg) {
            if ((this.MQSociedadesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MQSociedadesCompleted(this, new MQSociedadesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSMQ/WSMQ/MQHistorico", RequestNamespace="http://tempuri.org/WSMQ/WSMQ", ResponseNamespace="http://tempuri.org/WSMQ/WSMQ", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MQHistorico(string Mensaje) {
            object[] results = this.Invoke("MQHistorico", new object[] {
                        Mensaje});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MQHistoricoAsync(string Mensaje) {
            this.MQHistoricoAsync(Mensaje, null);
        }
        
        /// <remarks/>
        public void MQHistoricoAsync(string Mensaje, object userState) {
            if ((this.MQHistoricoOperationCompleted == null)) {
                this.MQHistoricoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMQHistoricoOperationCompleted);
            }
            this.InvokeAsync("MQHistorico", new object[] {
                        Mensaje}, this.MQHistoricoOperationCompleted, userState);
        }
        
        private void OnMQHistoricoOperationCompleted(object arg) {
            if ((this.MQHistoricoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MQHistoricoCompleted(this, new MQHistoricoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSMQ/WSMQ/MQPAF", RequestNamespace="http://tempuri.org/WSMQ/WSMQ", ResponseNamespace="http://tempuri.org/WSMQ/WSMQ", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MQPAF(string Mensaje) {
            object[] results = this.Invoke("MQPAF", new object[] {
                        Mensaje});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MQPAFAsync(string Mensaje) {
            this.MQPAFAsync(Mensaje, null);
        }
        
        /// <remarks/>
        public void MQPAFAsync(string Mensaje, object userState) {
            if ((this.MQPAFOperationCompleted == null)) {
                this.MQPAFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMQPAFOperationCompleted);
            }
            this.InvokeAsync("MQPAF", new object[] {
                        Mensaje}, this.MQPAFOperationCompleted, userState);
        }
        
        private void OnMQPAFOperationCompleted(object arg) {
            if ((this.MQPAFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MQPAFCompleted(this, new MQPAFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSMQ/WSMQ/BUSMQSICC00", RequestNamespace="http://tempuri.org/WSMQ/WSMQ", ResponseNamespace="http://tempuri.org/WSMQ/WSMQ", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BUSMQSICC00(string Mensaje) {
            object[] results = this.Invoke("BUSMQSICC00", new object[] {
                        Mensaje});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BUSMQSICC00Async(string Mensaje) {
            this.BUSMQSICC00Async(Mensaje, null);
        }
        
        /// <remarks/>
        public void BUSMQSICC00Async(string Mensaje, object userState) {
            if ((this.BUSMQSICC00OperationCompleted == null)) {
                this.BUSMQSICC00OperationCompleted = new System.Threading.SendOrPostCallback(this.OnBUSMQSICC00OperationCompleted);
            }
            this.InvokeAsync("BUSMQSICC00", new object[] {
                        Mensaje}, this.BUSMQSICC00OperationCompleted, userState);
        }
        
        private void OnBUSMQSICC00OperationCompleted(object arg) {
            if ((this.BUSMQSICC00Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BUSMQSICC00Completed(this, new BUSMQSICC00CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void MQSistarCompletedEventHandler(object sender, MQSistarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MQSistarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MQSistarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void MQPrestCompletedEventHandler(object sender, MQPrestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MQPrestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MQPrestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void MQTarjetasCompletedEventHandler(object sender, MQTarjetasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MQTarjetasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MQTarjetasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void MQLOGONCompletedEventHandler(object sender, MQLOGONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MQLOGONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MQLOGONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void MQCDPSCompletedEventHandler(object sender, MQCDPSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MQCDPSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MQCDPSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void MQSICC00CompletedEventHandler(object sender, MQSICC00CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MQSICC00CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MQSICC00CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void MQTASACIONCompletedEventHandler(object sender, MQTASACIONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MQTASACIONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MQTASACIONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void MQPJCompletedEventHandler(object sender, MQPJCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MQPJCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MQPJCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void MQMarchamosCompletedEventHandler(object sender, MQMarchamosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MQMarchamosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MQMarchamosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void MQConectividadesCompletedEventHandler(object sender, MQConectividadesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MQConectividadesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MQConectividadesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void MQSociedadesCompletedEventHandler(object sender, MQSociedadesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MQSociedadesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MQSociedadesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void MQHistoricoCompletedEventHandler(object sender, MQHistoricoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MQHistoricoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MQHistoricoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void MQPAFCompletedEventHandler(object sender, MQPAFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MQPAFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MQPAFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void BUSMQSICC00CompletedEventHandler(object sender, BUSMQSICC00CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BUSMQSICC00CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BUSMQSICC00CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591