
ALTER TABLE dbo.CAT_CATALOGO
	ADD CONSTRAINT  PK_CAT_CATALOGO PRIMARY KEY (cat_catalogo  ASC)
go



ALTER TABLE dbo.CAT_ELEMENTO
	ADD CONSTRAINT  PK_CAT_ELEMENTO PRIMARY KEY (cat_elemento  ASC)
go



ALTER TABLE dbo.CAT_INDICES_ACTUALIZACION_AVALUO
	ADD CONSTRAINT  CAT_INDICES_ACTUALIZACION_AVALUOS_PK PRIMARY KEY (Fecha_Hora  ASC)
go



ALTER TABLE dbo.GAR_CAPACIDAD_PAGO
	ADD CONSTRAINT  PK_GAR_HISTORICO_CAPACIDAD_PAGO PRIMARY KEY (cedula_deudor  ASC,fecha_capacidad_pago  ASC)
go



ALTER TABLE dbo.GAR_DEUDOR
	ADD CONSTRAINT  PK_GAR_DEUDOR PRIMARY KEY (cedula_deudor  ASC)
go



ALTER TABLE dbo.GAR_EJECUCION_PROCESO
	ADD CONSTRAINT  GAR_EJECUCION_PROCESO_UN PRIMARY KEY (conEjecucionProceso  ASC)
go



ALTER TABLE dbo.GAR_EJECUCION_PROCESO_DETALLE
	ADD CONSTRAINT  GAR_EJECUCION_PROCESO_DETALLE_UN PRIMARY KEY (conEjecucionProceso  ASC,conEjecucionProcesoDetalle  ASC)
go



ALTER TABLE dbo.GAR_EMPRESA
	ADD CONSTRAINT  PK_GAR_EMPRESA_CONSULTORA PRIMARY KEY (cedula_empresa  ASC)
go



ALTER TABLE dbo.GAR_GARANTIA_FIDUCIARIA
	ADD CONSTRAINT  PK_GAR_GARANTIA_FIDUCIARIA PRIMARY KEY (cod_garantia_fiduciaria  ASC)
go



ALTER TABLE dbo.GAR_GARANTIA_FIDUCIARIA
	ADD CONSTRAINT  IDX_LLAVE UNIQUE (cod_tipo_garantia  ASC,cod_clase_garantia  ASC,cedula_fiador  ASC)
go



ALTER TABLE dbo.GAR_GARANTIA_REAL
	ADD CONSTRAINT  PK_GAR_GARANTIA_REAL_1 PRIMARY KEY (cod_garantia_real  ASC)
go



ALTER TABLE dbo.GAR_GARANTIA_REAL
	ADD CONSTRAINT  GAR_GARANTIA_REAL_UK_01 UNIQUE (cod_tipo_garantia  ASC,cod_clase_garantia  ASC,cod_partido  ASC,numero_finca  ASC,cod_garantia_real  ASC,cod_tipo_garantia_real  ASC,cod_grado  ASC,cedula_hipotecaria  ASC,cod_clase_bien  ASC,num_placa_bien  ASC)
go



ALTER TABLE dbo.GAR_GARANTIA_VALOR
	ADD CONSTRAINT  PK_GAR_GARANTIA_VALOR_1 PRIMARY KEY (cod_garantia_valor  ASC)
go



ALTER TABLE dbo.GAR_GARANTIAS_FIDUCIARIAS_X_OPERACION
	ADD CONSTRAINT  PK_GAR_GARANTIAS_FIDUCIARIAS_X_OPERACION PRIMARY KEY (cod_operacion  ASC,cod_garantia_fiduciaria  ASC)
go



ALTER TABLE dbo.GAR_GARANTIAS_REALES_X_OPERACION
	ADD CONSTRAINT  PK_GAR_GARANTIAS_REALES_X_OPERACION PRIMARY KEY (cod_operacion  ASC,cod_garantia_real  ASC)
go



ALTER TABLE dbo.GAR_GARANTIAS_VALOR_X_OPERACION
	ADD CONSTRAINT  PK_GAR_GARANTIAS_VALOR_X_OPERACION PRIMARY KEY (cod_operacion  ASC,cod_garantia_valor  ASC)
go



ALTER TABLE dbo.GAR_GARANTIAS_X_GIRO
	ADD CONSTRAINT  PK_GAR_GIROS_X_OPERACION PRIMARY KEY (cod_operacion_giro  ASC,cod_operacion  ASC,cod_garantia  ASC,cod_tipo_garantia  ASC)
go



ALTER TABLE dbo.GAR_GARANTIAS_x_PERFIL_X_TARJETA
	ADD CONSTRAINT  PK_GAR_GARANTIAS_x_PERFIL_X_TARJET PRIMARY KEY (cod_tarjeta  ASC)
go



ALTER TABLE dbo.GAR_GIROS_GARANTIAS_REALES
	ADD CONSTRAINT  PK_GAR_GIROS_GARANTIAS_REALES UNIQUE (cod_llave  ASC)
go



ALTER TABLE dbo.GAR_OPERACION
	ADD CONSTRAINT  PK_GAR_OPERACIONES PRIMARY KEY (cod_operacion  ASC)
go



ALTER TABLE dbo.GAR_PERITO
	ADD CONSTRAINT  PK_GAR_PERITO PRIMARY KEY (cedula_perito  ASC)
go



ALTER TABLE dbo.GAR_PROCESO
	ADD CONSTRAINT  GAR_PROCESO_UN PRIMARY KEY (cocProceso  ASC)
go



ALTER TABLE dbo.GAR_VALUACIONES_FIADOR
	ADD CONSTRAINT  PK_GAR_VALUACIONES_FIADOR PRIMARY KEY (cod_garantia_fiduciaria  ASC,fecha_valuacion  ASC)
go



ALTER TABLE dbo.GAR_VALUACIONES_REALES
	ADD CONSTRAINT  PK_GAR_VALUACIONES_REALES PRIMARY KEY (cod_garantia_real  ASC,fecha_valuacion  ASC)
go



ALTER TABLE dbo.RPT_AVANCE_CONTRATOS_X_OFICINA_CLIENTE
	ADD CONSTRAINT  PK_RPT_AVANCE_CONTRATOS_X_OFICINA_CLIENTE PRIMARY KEY (fecha_corte  ASC,cod_oficina  ASC)
go



ALTER TABLE dbo.RPT_AVANCE_OPERACION_X_OFICINA_CLIENTE
	ADD CONSTRAINT  PK_RPT_AVANCE_OPERACION_X_OFICINA_CLIENTE PRIMARY KEY (fecha_corte  ASC,cod_oficina  ASC)
go



ALTER TABLE dbo.RPT_AVANCE_X_OFICINA_CLIENTE
	ADD CONSTRAINT  PK_RPT_AVANCE_X_OFICINA_CLIENTE PRIMARY KEY (fecha_corte  ASC,cod_oficina  ASC)
go



ALTER TABLE dbo.RPT_CONTRATOS_AVANCE_X_OFICINA_CLIENTE
	ADD CONSTRAINT  PK_CONTRATOS_RPT_AVANCE_X_OFICINA_CLIENTE PRIMARY KEY (fecha_corte  ASC,cod_oficina  ASC)
go



ALTER TABLE dbo.SEG_PERFIL
	ADD CONSTRAINT  PK_SEG_PERFIL PRIMARY KEY (COD_PERFIL  ASC)
go



ALTER TABLE dbo.SEG_ROL
	ADD CONSTRAINT  PK_SEG_ROL PRIMARY KEY (COD_ROL  ASC)
go



ALTER TABLE dbo.SEG_ROLES_X_PERFIL
	ADD CONSTRAINT  PK_SEG_ROLES_X_PERFIL PRIMARY KEY (COD_PERFIL  ASC,COD_ROL  ASC)
go



ALTER TABLE dbo.SEG_USUARIO
	ADD CONSTRAINT  PK_SEG_USUARIO PRIMARY KEY (COD_USUARIO  ASC)
go



ALTER TABLE dbo.TAR_BIN_SISTAR
	ADD CONSTRAINT  Bines_Sistar_PK PRIMARY KEY (bin  ASC)
go



ALTER TABLE dbo.TAR_GARANTIA_FIDUCIARIA
	ADD CONSTRAINT  PK_TAR_GARANTIA_FIDUCIARIA PRIMARY KEY (cod_garantia_fiduciaria  ASC)
go



ALTER TABLE dbo.TAR_GARANTIAS_FIDUCIARIAS_X_TARJETA
	ADD CONSTRAINT  PK_TAR_GARANTIAS_FIDUCIARIAS_X_TARJETA PRIMARY KEY (cod_tarjeta  ASC,cod_garantia_fiduciaria  ASC)
go



ALTER TABLE dbo.TAR_GARANTIAS_X_PERFIL_X_TARJETA
	ADD CONSTRAINT  PK_GAR_GARANTIAS_x_PERFIL_X_TARJETA PRIMARY KEY (cod_tarjeta  ASC)
go



ALTER TABLE dbo.TAR_TARJETA
	ADD CONSTRAINT  PK_TAR_TARJETA PRIMARY KEY (cod_tarjeta  ASC)
go



ALTER TABLE dbo.TAR_TARJETA
	ADD CONSTRAINT  num_tarjeta_unica UNIQUE (num_tarjeta  ASC)
go



ALTER TABLE dbo.TMP_ARCHIVO_CONTRATOS
	ADD CONSTRAINT  TMP_ARCHIVO_CONTRATOS_UN UNIQUE (prmca_pco_ofici  ASC,prmca_pco_moned  ASC,prmca_pco_produc  ASC,prmca_pnu_contr  ASC,cod_usuario  ASC)
go



ALTER TABLE dbo.TMP_GARANTIAS_REALES_OPERACIONES
	ADD CONSTRAINT  TMP_GARANTIAS_REALES_OPERACIONES_PK PRIMARY KEY (Codigo_Llave  ASC)
go




ALTER TABLE dbo.CAT_ELEMENTO
	ADD CONSTRAINT  FK_CAT_ELEMENTO_CAT_CATALOGO FOREIGN KEY (cat_catalogo) REFERENCES dbo.CAT_CATALOGO(cat_catalogo)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE dbo.GAR_CAPACIDAD_PAGO
	ADD CONSTRAINT  FK_GAR_HISTORICO_CAPACIDAD_PAGO_GAR_DEUDOR FOREIGN KEY (cedula_deudor) REFERENCES dbo.GAR_DEUDOR(cedula_deudor)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE dbo.GAR_EJECUCION_PROCESO
	ADD CONSTRAINT  FK_GAR_EJECUCION_PROCESO_GAR_PROCESO1 FOREIGN KEY (cocProceso) REFERENCES dbo.GAR_PROCESO(cocProceso)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE dbo.GAR_EJECUCION_PROCESO_DETALLE
	ADD CONSTRAINT  FK_GAR_EJECUCION_PROCESO_DETALLE_GAR_EJECUCION_PROCESO1 FOREIGN KEY (conEjecucionProceso) REFERENCES dbo.GAR_EJECUCION_PROCESO(conEjecucionProceso)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE dbo.GAR_GARANTIAS_FIDUCIARIAS_X_OPERACION
	ADD CONSTRAINT  FK_GAR_GARANTIAS_FIDUCIARIAS_X_OPERACION_GAR_GARANTIA_FIDUCIARIA FOREIGN KEY (cod_garantia_fiduciaria) REFERENCES dbo.GAR_GARANTIA_FIDUCIARIA(cod_garantia_fiduciaria)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go


ALTER TABLE dbo.GAR_GARANTIAS_FIDUCIARIAS_X_OPERACION
	ADD CONSTRAINT  FK_GAR_GARANTIAS_FIDUCIARIAS_X_OPERACION_GAR_OPERACION FOREIGN KEY (cod_operacion) REFERENCES dbo.GAR_OPERACION(cod_operacion)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE dbo.GAR_GARANTIAS_REALES_X_OPERACION
	ADD CONSTRAINT  FK_GAR_GARANTIAS_REALES_X_OPERACION_GAR_GARANTIA_REAL FOREIGN KEY (cod_garantia_real) REFERENCES dbo.GAR_GARANTIA_REAL(cod_garantia_real)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go


ALTER TABLE dbo.GAR_GARANTIAS_REALES_X_OPERACION
	ADD CONSTRAINT  FK_GAR_GARANTIAS_REALES_X_OPERACION_GAR_OPERACION FOREIGN KEY (cod_operacion) REFERENCES dbo.GAR_OPERACION(cod_operacion)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE dbo.GAR_GARANTIAS_VALOR_X_OPERACION
	ADD CONSTRAINT  FK_GAR_GARANTIAS_VALOR_X_OPERACION_GAR_GARANTIA_VALOR FOREIGN KEY (cod_garantia_valor) REFERENCES dbo.GAR_GARANTIA_VALOR(cod_garantia_valor)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go


ALTER TABLE dbo.GAR_GARANTIAS_VALOR_X_OPERACION
	ADD CONSTRAINT  FK_GAR_GARANTIAS_VALOR_X_OPERACION_GAR_OPERACION FOREIGN KEY (cod_operacion) REFERENCES dbo.GAR_OPERACION(cod_operacion)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE dbo.GAR_GARANTIAS_X_GIRO
	ADD CONSTRAINT  FK_GAR_GARANTIAS_X_GIRO_GAR_OPERACION1 FOREIGN KEY (cod_operacion_giro) REFERENCES dbo.GAR_OPERACION(cod_operacion)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE dbo.GAR_OPERACION
	ADD CONSTRAINT  FK_GAR_OPERACION_GAR_DEUDOR1 FOREIGN KEY (cedula_deudor) REFERENCES dbo.GAR_DEUDOR(cedula_deudor)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE dbo.GAR_VALUACIONES_FIADOR
	ADD CONSTRAINT  FK_GAR_VALUACIONES_FIADOR_GAR_GARANTIA_FIDUCIARIA FOREIGN KEY (cod_garantia_fiduciaria) REFERENCES dbo.GAR_GARANTIA_FIDUCIARIA(cod_garantia_fiduciaria)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE dbo.GAR_VALUACIONES_REALES
	ADD CONSTRAINT  FK_GAR_VALUACIONES_REALES_GAR_PERITO FOREIGN KEY (cedula_perito) REFERENCES dbo.GAR_PERITO(cedula_perito)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go


ALTER TABLE dbo.GAR_VALUACIONES_REALES
	ADD CONSTRAINT  FK_GAR_VALUACIONES_REALES_GAR_EMPRESA FOREIGN KEY (cedula_empresa) REFERENCES dbo.GAR_EMPRESA(cedula_empresa)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go


ALTER TABLE dbo.GAR_VALUACIONES_REALES
	ADD CONSTRAINT  FK_GAR_VALUACIONES_REALES_GAR_GARANTIA_REAL FOREIGN KEY (cod_garantia_real) REFERENCES dbo.GAR_GARANTIA_REAL(cod_garantia_real)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE dbo.SEG_ROLES_X_PERFIL
	ADD CONSTRAINT  FK_SEG_ROLES_X_PERFIL_SEG_ROL FOREIGN KEY (COD_ROL) REFERENCES dbo.SEG_ROL(COD_ROL)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go


ALTER TABLE dbo.SEG_ROLES_X_PERFIL
	ADD CONSTRAINT  FK_SEG_ROLES_X_PERFIL_SEG_PERFIL FOREIGN KEY (COD_PERFIL) REFERENCES dbo.SEG_PERFIL(COD_PERFIL)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE dbo.SEG_USUARIO
	ADD CONSTRAINT  FK_SEG_USUARIO_SEG_PERFIL FOREIGN KEY (COD_PERFIL) REFERENCES dbo.SEG_PERFIL(COD_PERFIL)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE dbo.TAR_GARANTIAS_FIDUCIARIAS_X_TARJETA
	ADD CONSTRAINT  FK_TAR_GARANTIAS_FIDUCIARIAS_X_TARJETA_TAR_GARANTIA_FIDUCIARIA FOREIGN KEY (cod_garantia_fiduciaria) REFERENCES dbo.TAR_GARANTIA_FIDUCIARIA(cod_garantia_fiduciaria)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go


ALTER TABLE dbo.TAR_GARANTIAS_FIDUCIARIAS_X_TARJETA
	ADD CONSTRAINT  FK_TAR_GARANTIAS_FIDUCIARIAS_X_TARJETA_TAR_TARJETA FOREIGN KEY (cod_tarjeta) REFERENCES dbo.TAR_TARJETA(cod_tarjeta)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE dbo.TAR_GARANTIAS_X_PERFIL_X_TARJETA
	ADD CONSTRAINT  FK_TAR_GARANTIAS_X_PERFIL_X_TARJETA_X_TARJETA_TAR_TARJETA FOREIGN KEY (cod_tarjeta) REFERENCES dbo.TAR_TARJETA(cod_tarjeta)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




ALTER TABLE dbo.TAR_TARJETA
	ADD CONSTRAINT  FK_TAR_TARJETA_GAR_DEUDOR FOREIGN KEY (cedula_deudor) REFERENCES dbo.GAR_DEUDOR(cedula_deudor)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go


ALTER TABLE dbo.CAT_TIPOS_POLIZAS_SUGEF
	ADD CONSTRAINT  CAT_TIPOS_POLIZAS_SUGEF_PK PRIMARY KEY (Codigo_Tipo_Poliza_Sugef  ASC)
GO



ALTER TABLE dbo.CAT_TIPOS_POLIZAS_X_TIPO_BIEN
	ADD CONSTRAINT  CAT_TIPOS_POLIZAS_X_TIPO_BIEN_PK PRIMARY KEY (Consecutivo_Relacion  ASC)
GO



ALTER TABLE dbo.CAT_TIPOS_POLIZAS_X_TIPO_BIEN
	ADD CONSTRAINT  CAT_TIPOS_POLIZAS_X_TIPO_BIEN_UK_01 UNIQUE (Codigo_Tipo_Poliza_Sugef  ASC,Codigo_Tipo_Bien  ASC,Codigo_Tipo_Poliza_Sap  ASC)
GO



ALTER TABLE dbo.GAR_POLIZAS
	ADD CONSTRAINT  GAR_POLIZAS_PK PRIMARY KEY (Codigo_SAP  ASC,cod_operacion  ASC)
GO



ALTER TABLE dbo.GAR_POLIZAS
	ADD CONSTRAINT  GAR_POLIZAS_UK_01 UNIQUE (Codigo_SAP  ASC,cod_operacion  ASC,Tipo_Poliza  ASC)
GO



ALTER TABLE dbo.GAR_POLIZAS_RELACIONADAS
	ADD CONSTRAINT  GAR_POLIZAS_RELACIONADAS_PK PRIMARY KEY (Codigo_SAP  ASC,cod_operacion  ASC,cod_garantia_real  ASC)
GO



ALTER TABLE dbo.GAR_POLIZAS
	ADD CONSTRAINT  GAR_OPERACIONES_FK_GAR_POLIZAS FOREIGN KEY (cod_operacion) REFERENCES dbo.GAR_OPERACION(cod_operacion)
		ON UPDATE NO ACTION
GO




ALTER TABLE dbo.GAR_POLIZAS_RELACIONADAS
	ADD CONSTRAINT  GAR_GARANTIA_REAL_FK_GAR_POLIZAS_RELACIONADAS FOREIGN KEY (cod_garantia_real) REFERENCES dbo.GAR_GARANTIA_REAL(cod_garantia_real)
		ON UPDATE NO ACTION
GO


ALTER TABLE dbo.GAR_POLIZAS_RELACIONADAS
	ADD CONSTRAINT  GAR_POLIZAS_FK_GAR_POLIZAS_RELACIONADAS FOREIGN KEY (Codigo_SAP,cod_operacion) REFERENCES dbo.GAR_POLIZAS(Codigo_SAP,cod_operacion)
		ON UPDATE NO ACTION
GO

