
CREATE  UNIQUE  CLUSTERED INDEX PK_CAT_CATALOGO ON dbo.CAT_CATALOGO
(
	cat_catalogo          ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  UNIQUE  CLUSTERED INDEX PK_CAT_ELEMENTO ON dbo.CAT_ELEMENTO
(
	cat_elemento          ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  UNIQUE  CLUSTERED INDEX CAT_INDICES_ACTUALIZACION_AVALUOS_PK ON dbo.CAT_INDICES_ACTUALIZACION_AVALUO
(
	Fecha_Hora            ASC
)
 ON "PRIMARY"
go



CREATE  UNIQUE  CLUSTERED INDEX PK_GAR_HISTORICO_CAPACIDAD_PAGO ON dbo.GAR_CAPACIDAD_PAGO
(
	cedula_deudor         ASC,
	fecha_capacidad_pago  ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  UNIQUE  CLUSTERED INDEX PK_GAR_DEUDOR ON dbo.GAR_DEUDOR
(
	cedula_deudor         ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  UNIQUE  NONCLUSTERED INDEX GAR_EJECUCION_PROCESO_UN ON dbo.GAR_EJECUCION_PROCESO
(
	conEjecucionProceso   ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  UNIQUE  NONCLUSTERED INDEX GAR_EJECUCION_PROCESO_DETALLE_UN ON dbo.GAR_EJECUCION_PROCESO_DETALLE
(
	conEjecucionProceso   ASC,
	conEjecucionProcesoDetalle  ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  UNIQUE  CLUSTERED INDEX PK_GAR_EMPRESA_CONSULTORA ON dbo.GAR_EMPRESA
(
	cedula_empresa        ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  UNIQUE  CLUSTERED INDEX PK_GAR_GARANTIA_FIDUCIARIA ON dbo.GAR_GARANTIA_FIDUCIARIA
(
	cod_garantia_fiduciaria  ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  UNIQUE  NONCLUSTERED INDEX IDX_LLAVE ON dbo.GAR_GARANTIA_FIDUCIARIA
(
	cod_tipo_garantia     ASC,
	cod_clase_garantia    ASC,
	cedula_fiador         ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go

CREATE NONCLUSTERED INDEX GAR_GARANTIA_FIDUCIARIA_IX_03 ON dbo.GAR_GARANTIA_FIDUCIARIA
(
	Identificacion_Sicc		ASC
)
ON [PRIMARY]
GO


CREATE  UNIQUE  CLUSTERED INDEX PK_GAR_GARANTIA_REAL_1 ON dbo.GAR_GARANTIA_REAL
(
	cod_garantia_real     ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  UNIQUE  NONCLUSTERED INDEX GAR_GARANTIA_REAL_UK_01 ON dbo.GAR_GARANTIA_REAL
(
	cod_tipo_garantia     ASC,
	cod_clase_garantia    ASC,
	cod_partido           ASC,
	numero_finca          ASC,
	cod_garantia_real     ASC,
	cod_tipo_garantia_real  ASC,
	cod_grado             ASC,
	cedula_hipotecaria    ASC,
	cod_clase_bien        ASC,
	num_placa_bien        ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go

CREATE NONCLUSTERED INDEX GAR_GARANTIA_REAL_IX_02 ON dbo.GAR_GARANTIA_REAL
(
	cod_clase_garantia	ASC,
	Identificacion_Sicc ASC
)
ON [PRIMARY]
GO


CREATE  UNIQUE  CLUSTERED INDEX PK_GAR_GARANTIA_VALOR_1 ON dbo.GAR_GARANTIA_VALOR
(
	cod_garantia_valor    ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go

CREATE NONCLUSTERED INDEX GAR_GARANTIA_VALOR_IX_01 ON dbo.GAR_GARANTIA_VALOR
(
	Identificacion_Sicc ASC
)
ON [PRIMARY]
GO

CREATE  UNIQUE  CLUSTERED INDEX PK_GAR_GARANTIAS_FIDUCIARIAS_X_OPERACION ON dbo.GAR_GARANTIAS_FIDUCIARIAS_X_OPERACION
(
	cod_operacion         ASC,
	cod_garantia_fiduciaria  ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  UNIQUE  CLUSTERED INDEX PK_GAR_GARANTIAS_REALES_X_OPERACION ON dbo.GAR_GARANTIAS_REALES_X_OPERACION
(
	cod_operacion         ASC,
	cod_garantia_real     ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  UNIQUE  CLUSTERED INDEX PK_GAR_GARANTIAS_VALOR_X_OPERACION ON dbo.GAR_GARANTIAS_VALOR_X_OPERACION
(
	cod_operacion         ASC,
	cod_garantia_valor    ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  UNIQUE  CLUSTERED INDEX PK_GAR_GIROS_X_OPERACION ON dbo.GAR_GARANTIAS_X_GIRO
(
	cod_operacion_giro    ASC,
	cod_operacion         ASC,
	cod_garantia          ASC,
	cod_tipo_garantia     ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  UNIQUE  CLUSTERED INDEX PK_GAR_GARANTIAS_x_PERFIL_X_TARJET ON dbo.GAR_GARANTIAS_x_PERFIL_X_TARJETA
(
	cod_tarjeta           ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  UNIQUE  NONCLUSTERED INDEX PK_GAR_GIROS_GARANTIAS_REALES ON dbo.GAR_GIROS_GARANTIAS_REALES
(
	cod_llave             ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  UNIQUE  CLUSTERED INDEX PK_GAR_OPERACIONES ON dbo.GAR_OPERACION
(
	cod_operacion         ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  NONCLUSTERED INDEX GAR_OPERACION_IX_01 ON dbo.GAR_OPERACION
(
	cod_oficina           ASC,
	cod_moneda            ASC,
	cod_producto          ASC,
	num_operacion         ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  NONCLUSTERED INDEX GAR_OPERACION_IX_02 ON dbo.GAR_OPERACION
(
	cod_oficina           ASC,
	cod_moneda            ASC,
	cod_producto          ASC,
	num_contrato          ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  UNIQUE  CLUSTERED INDEX PK_GAR_PERITO ON dbo.GAR_PERITO
(
	cedula_perito         ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  UNIQUE  NONCLUSTERED INDEX GAR_PROCESO_UN ON dbo.GAR_PROCESO
(
	cocProceso            ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  CLUSTERED INDEX GAR_SICC_BSMPC_NC ON dbo.GAR_SICC_BSMPC
(
	bsmpc_sco_ident       ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  CLUSTERED INDEX GAR_SICC_PRMCA_IX_01 ON dbo.GAR_SICC_PRMCA
(
	prmca_pnu_contr       ASC,
	prmca_pco_ofici       ASC,
	prmca_pco_moned       ASC,
	prmca_pco_produc      ASC,
	prmca_pco_conta       ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go

CREATE NONCLUSTERED INDEX GAR_SICC_PRMCA_IX_02 ON dbo.GAR_SICC_PRMCA
(
	 prmca_estado	ASC
)
ON [PRIMARY]
GO

CREATE  CLUSTERED INDEX GAR_SICC_PRMGT_IX_01 ON dbo.GAR_SICC_PRMGT
(
	prmgt_pnu_oper        ASC,
	prmgt_pco_ofici       ASC,
	prmgt_pco_moned       ASC,
	prmgt_pco_produ       ASC,
	prmgt_pco_conta       ASC,
	prmgt_pnuidegar       ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go

CREATE NONCLUSTERED INDEX GAR_SICC_PRMGT_IX_02 ON dbo.GAR_SICC_PRMGT
(
	 prmgt_estado		ASC,
	 prmgt_pcoclagar	ASC
)
ON [PRIMARY]
GO

CREATE  CLUSTERED INDEX GAR_SICC_PRMOC_IX_01 ON dbo.GAR_SICC_PRMOC
(
	prmoc_pnu_oper        ASC,
	prmoc_dco_ofici       ASC,
	prmoc_pco_moned       ASC,
	prmoc_pco_produ       ASC,
	prmoc_pco_conta       ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go

CREATE NONCLUSTERED INDEX GAR_SICC_PRMOC_IX_02 ON dbo.GAR_SICC_PRMOC
(
	 prmoc_pse_proces	ASC,
	 prmoc_estado		ASC
)
ON [PRIMARY]
GO

CREATE  CLUSTERED INDEX GAR_SICC_PRMRI_IX_01 ON dbo.GAR_SICC_PRMRI
(
	prmri_pnu_opera       ASC,
	prmri_pco_ofici       ASC,
	prmri_pco_moned       ASC,
	prmri_pco_produ       ASC,
	prmri_pco_conta       ASC,
	prmri_pnuidegar       ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go

CREATE NONCLUSTERED INDEX GAR_SICC_PRMRI_IX_02 ON dbo.GAR_SICC_PRMRI
(
	prmri_estado	ASC
)
ON [PRIMARY]
GO

CREATE  UNIQUE  CLUSTERED INDEX PK_GAR_VALUACIONES_FIADOR ON dbo.GAR_VALUACIONES_FIADOR
(
	cod_garantia_fiduciaria  ASC,
	fecha_valuacion       ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  UNIQUE  CLUSTERED INDEX PK_GAR_VALUACIONES_REALES ON dbo.GAR_VALUACIONES_REALES
(
	cod_garantia_real     ASC,
	fecha_valuacion       ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  NONCLUSTERED INDEX GAR_VALUACIONES_REALES_IX_01 ON dbo.GAR_VALUACIONES_REALES
(
	cod_garantia_real     ASC,
	fecha_valuacion       ASC,
	Indicador_Tipo_Registro  ASC,
	Indicador_Actualizado_Calculo  ASC
)
 ON "PRIMARY"
go



CREATE  UNIQUE  CLUSTERED INDEX PK_RPT_AVANCE_CONTRATOS_X_OFICINA_CLIENTE ON dbo.RPT_AVANCE_CONTRATOS_X_OFICINA_CLIENTE
(
	fecha_corte           ASC,
	cod_oficina           ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  UNIQUE  CLUSTERED INDEX PK_RPT_AVANCE_OPERACION_X_OFICINA_CLIENTE ON dbo.RPT_AVANCE_OPERACION_X_OFICINA_CLIENTE
(
	fecha_corte           ASC,
	cod_oficina           ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  UNIQUE  CLUSTERED INDEX PK_RPT_AVANCE_X_OFICINA_CLIENTE ON dbo.RPT_AVANCE_X_OFICINA_CLIENTE
(
	fecha_corte           ASC,
	cod_oficina           ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  UNIQUE  CLUSTERED INDEX PK_CONTRATOS_RPT_AVANCE_X_OFICINA_CLIENTE ON dbo.RPT_CONTRATOS_AVANCE_X_OFICINA_CLIENTE
(
	fecha_corte           ASC,
	cod_oficina           ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  UNIQUE  CLUSTERED INDEX PK_SEG_PERFIL ON dbo.SEG_PERFIL
(
	COD_PERFIL            ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  UNIQUE  CLUSTERED INDEX PK_SEG_ROL ON dbo.SEG_ROL
(
	COD_ROL               ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  UNIQUE  CLUSTERED INDEX PK_SEG_ROLES_X_PERFIL ON dbo.SEG_ROLES_X_PERFIL
(
	COD_PERFIL            ASC,
	COD_ROL               ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  UNIQUE  CLUSTERED INDEX PK_SEG_USUARIO ON dbo.SEG_USUARIO
(
	COD_USUARIO           ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  UNIQUE  NONCLUSTERED INDEX Bines_Sistar_PK ON dbo.TAR_BIN_SISTAR
(
	bin                   ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  UNIQUE  CLUSTERED INDEX PK_TAR_GARANTIA_FIDUCIARIA ON dbo.TAR_GARANTIA_FIDUCIARIA
(
	cod_garantia_fiduciaria  ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  UNIQUE  CLUSTERED INDEX PK_TAR_GARANTIAS_FIDUCIARIAS_X_TARJETA ON dbo.TAR_GARANTIAS_FIDUCIARIAS_X_TARJETA
(
	cod_tarjeta           ASC,
	cod_garantia_fiduciaria  ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  UNIQUE  CLUSTERED INDEX PK_GAR_GARANTIAS_x_PERFIL_X_TARJETA ON dbo.TAR_GARANTIAS_X_PERFIL_X_TARJETA
(
	cod_tarjeta           ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  UNIQUE  CLUSTERED INDEX PK_TAR_TARJETA ON dbo.TAR_TARJETA
(
	cod_tarjeta           ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  UNIQUE  NONCLUSTERED INDEX num_tarjeta_unica ON dbo.TAR_TARJETA
(
	num_tarjeta           ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  UNIQUE  NONCLUSTERED INDEX TMP_ARCHIVO_CONTRATOS_UN ON dbo.TMP_ARCHIVO_CONTRATOS
(
	prmca_pco_ofici       ASC,
	prmca_pco_moned       ASC,
	prmca_pco_produc      ASC,
	prmca_pnu_contr       ASC,
	cod_usuario           ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  CLUSTERED INDEX TMP_GARANTIAS_FIDUCIARIAS_NC ON dbo.TMP_GARANTIAS_FIDUCIARIAS
(
	cod_usuario           ASC,
	cod_tipo_operacion    ASC,
	ind_duplicidad        ASC,
	cod_oficina           ASC,
	cod_moneda            ASC,
	cod_producto          ASC,
	operacion             ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  CLUSTERED INDEX TMP_GARANTIAS_REALES_NC ON dbo.TMP_GARANTIAS_REALES
(
	cod_usuario           ASC,
	cod_tipo_operacion    ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  UNIQUE  CLUSTERED INDEX TMP_GARANTIAS_REALES_OPERACIONES_PK ON dbo.TMP_GARANTIAS_REALES_OPERACIONES
(
	Codigo_Llave          ASC
)
 ON "PRIMARY"
go



CREATE  NONCLUSTERED INDEX TMP_GARANTIAS_REALES_X_OPERACION_IX_01 ON dbo.TMP_GARANTIAS_REALES_X_OPERACION
(
	Codigo_Usuario        ASC,
	Codigo_Tipo_Operacion  ASC,
	Codigo_Tipo_Garantia_Real  ASC
)
 ON "PRIMARY"
go



CREATE  CLUSTERED INDEX TMP_GARANTIAS_VALOR_NC ON dbo.TMP_GARANTIAS_VALOR
(
	cod_usuario           ASC,
	cod_tipo_operacion    ASC,
	ind_duplicidad        ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  CLUSTERED INDEX TMP_OPERACIONES_NC ON dbo.TMP_OPERACIONES
(
	cod_tipo_garantia     ASC,
	cod_tipo_operacion    ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  CLUSTERED INDEX TMP_OPERACIONES_DUPLICADAS_NC ON dbo.TMP_OPERACIONES_DUPLICADAS
(
	cod_usuario           ASC,
	cod_tipo_garantia     ASC,
	cod_tipo_operacion    ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go



CREATE  CLUSTERED INDEX TMP_VALUACIONES_REALES_NC ON dbo.TMP_VALUACIONES_REALES
(
	cod_usuario           ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go


CREATE NONCLUSTERED INDEX GAR_SICC_DAMHT_IX_01 ON dbo.GAR_SICC_DAMHT
(
	 damht_aco_estado ASC,
	 damht_dcotipcam ASC,
	 damht_dco_moned ASC,
	 damht_dfe_inic ASC
)
 WITH 
	FILLFACTOR =90
 ON "PRIMARY"
go


CREATE  NONCLUSTERED INDEX GAR_POLIZAS_IX_02 ON dbo.GAR_POLIZAS
(
	Estado_Registro       ASC
)
GO


CREATE UNIQUE NONCLUSTERED INDEX CAT_ELEMENTO_UK_01 ON dbo.CAT_ELEMENTO
(
	cat_catalogo ASC,
	cat_campo ASC
)
GO

CREATE UNIQUE NONCLUSTERED INDEX [CAT_PORCENTAJE_ACEPTACION_UK_01] ON [dbo].[CAT_PORCENTAJE_ACEPTACION] 
(
	[Codigo_Tipo_Garantia] ASC,
	[Codigo_Tipo_Mitigador] ASC
)ON [PRIMARY]
GO


CREATE CLUSTERED INDEX [PORCENTAJE_ACEPTACION_HST_IX_01] ON [dbo].[PORCENTAJE_ACEPTACION_HST] 
(
	[Codigo_Usuario] ASC,
	[Fecha_Hora] ASC
)ON [PRIMARY]
GO

CREATE CLUSTERED INDEX [GAR_BITACORA_IX_01] ON [dbo].[GAR_BITACORA] 
(
	fecha_hora ASC,
	des_tabla ASC
)ON [PRIMARY]
GO


CREATE CLUSTERED INDEX TMP_GIROS_CONTRATOS_IX_01 ON dbo.TMP_GIROS_CONTRATOS
(
	Registro_Activo ASC,
	Usuario ASC
) ON [PRIMARY]
GO

CREATE CLUSTERED INDEX TMP_CALCULO_MTAT_MTANT_IX_01 ON dbo.TMP_CALCULO_MTAT_MTANT
(
	Usuario ASC,
	Fecha_Hora ASC
) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX TMP_CALCULO_MTAT_MTANT_IX_02 ON dbo.TMP_CALCULO_MTAT_MTANT 
(
	Usuario ASC,
	Codigo_Operacion ASC,
	Codigo_Garantia ASC
)ON [PRIMARY]
GO

CREATE CLUSTERED INDEX SICAD_FIDUCIARIAS_IX_01 ON dbo.SICAD_FIDUCIARIAS
( 
	ID_GARANTIA_FIDUCIARIA  ASC,
	TIPO_PERSONA          ASC
)
GO



CREATE CLUSTERED INDEX SICAD_GAROPER_IX_01 ON dbo.SICAD_GAROPER
( 
	ID_OPERACION          ASC
)
GO



CREATE CLUSTERED INDEX SICAD_GAROPER_GRAVAMEN_IX_01 ON dbo.SICAD_GAROPER_GRAVAMEN
( 
	ID_OPERACION          ASC,
	ID_GARANTIA           ASC,
	TIPO_MITIGADOR        ASC,
	TIPO_DOCUMENTO_LEGAL  ASC,
	GRADO_GRAVAMENES      ASC
)
GO



CREATE CLUSTERED INDEX SICAD_GAROPER_LISTA_IX_01 ON dbo.SICAD_GAROPER_LISTA
( 
	ID_OPERACION          ASC,
	ID_GARANTIA           ASC,
	TIPO_GARANTIA         ASC
)
GO



CREATE CLUSTERED INDEX SICAD_REALES_IX_01 ON dbo.SICAD_REALES
( 
	ID_GARANTIA_REAL      ASC,
	TIPO_BIEN_GARANTIA_REAL  ASC
)
GO



CREATE CLUSTERED INDEX SICAD_REALES_POLIZA_IX_01 ON dbo.SICAD_REALES_POLIZA
( 
	ID_GARANTIA_REAL      ASC,
	TIPO_POLIZA_GARANTIA_REAL  ASC
)
GO



CREATE CLUSTERED INDEX SICAD_VALORES_IX_01 ON dbo.SICAD_VALORES
( 
	ID_GARANTIA_VALOR     ASC,
	CLASIFICACION_INSTRUMENTO  ASC,
	TIPO_PERSONA          ASC,
	ID_EMISOR             ASC,
	ID_INSTRUMENTO        ASC,
	SERIE_INSTRUMENTO     ASC,
	PREMIO                ASC,
	VALOR_FACIAL          ASC,
	TIPO_MONEDA_VALOR_FACIAL  ASC,
	VALOR_MERCADO         ASC,
	TIPO_MONEDA_VALOR_MERCADO  ASC,
	FECHA_CONSTITUCION    ASC,
	FECHA_VENCIMIENTO     ASC
)
GO

