GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.BCR_OFICINAS TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CAT_CATALOGO TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CAT_ELEMENTO TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CAT_INDICES_ACTUALIZACION_AVALUO TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CAT_INSTRUMENTOS TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CAT_ISIN TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_BITACORA TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_CAPACIDAD_PAGO TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_DEUDOR TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_EJECUCION_PROCESO TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_EJECUCION_PROCESO_DETALLE TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_EMPRESA TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_GARANTIA_FIDUCIARIA TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_GARANTIA_REAL TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_GARANTIA_VALOR TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_GARANTIAS_FIDUCIARIAS_X_OPERACION TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_GARANTIAS_REALES_X_OPERACION TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_GARANTIAS_VALOR_X_OPERACION TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_GARANTIAS_X_GIRO TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_GARANTIAS_x_PERFIL_X_TARJETA TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_GIROS_GARANTIAS_FIDUCIARIAS TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_GIROS_GARANTIAS_REALES TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_GIROS_GARANTIAS_VALOR TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_MIG_DEUDORES TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_OPERACION TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_PERITO TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_PROCESO TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_SICC_BSMCL TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_SICC_BSMPC TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_SICC_PRHCS TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_SICC_PRMCA TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_SICC_PRMGT TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_SICC_PRMOC TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_SICC_PRMRI TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_SICC_PRMSC TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_VALUACIONES_FIADOR TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_VALUACIONES_REALES TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.RPT_AVANCE_CONTRATOS_X_OFICINA_CLIENTE TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.RPT_AVANCE_OPERACION_X_OFICINA_CLIENTE TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.RPT_AVANCE_X_OFICINA_CLIENTE TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.RPT_CONTRATOS_AVANCE_X_OFICINA_CLIENTE TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.RPT_CONTRATOS_DETALLE_X_GARANTIA TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.RPT_DETALLE_X_CONTRATO TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.RPT_DETALLE_X_GARANTIA TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.RPT_DETALLE_X_OPERACION TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SEG_PERFIL TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SEG_ROL TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SEG_ROLES_X_PERFIL TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SEG_USUARIO TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TAR_BIN_SISTAR TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TAR_GARANTIA_FIDUCIARIA TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TAR_GARANTIAS_FIDUCIARIAS_X_TARJETA TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TAR_GARANTIAS_X_PERFIL_X_TARJETA TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TAR_TARJETA TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TAR_TARJETA_SICC TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TAR_TARJETA_SISTAR TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TMP_ARCHIVO_CONTRATOS TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TMP_CALCULO_MTAT_MTANT TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TMP_GAR_CONTRATOS TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TMP_GARANTIAS_FIDUCIARIAS TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TMP_GARANTIAS_REALES TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TMP_GARANTIAS_REALES_OPERACIONES TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TMP_GARANTIAS_REALES_X_OPERACION TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TMP_GARANTIAS_VALOR TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TMP_OPERACIONES TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TMP_OPERACIONES_DUPLICADAS TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TMP_VALUACIONES_REALES TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_SICC_DAMHT TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CAT_TIPOS_POLIZAS_SUGEF TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CAT_TIPOS_POLIZAS_X_TIPO_BIEN TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_POLIZAS TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_POLIZAS_RELACIONADAS TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TMP_POLIZAS TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CAT_PORCENTAJE_ACEPTACION TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.PORCENTAJE_ACEPTACION_HST TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GAR_BITACORA TO RAP_Reportes
GRANT SELECT, INSERT, UPDATE ON dbo.TMP_SAP_VWSGRPOLIZA TO RAP_Garantias
GRANT SELECT, INSERT, UPDATE ON dbo.TMP_SAP_VWSGRPOLIZACREDITOBANCARIO TO RAP_Garantias
GRANT SELECT, INSERT, UPDATE ON dbo.TMP_SAP_VWSGRPOLIZACONTRATOCREDITO TO RAP_Garantias
GRANT SELECT, INSERT, UPDATE ON dbo.TMP_SAP_POLIZASEXTERNAS TO RAP_Garantias
GRANT SELECT, INSERT, UPDATE ON dbo.TMP_SAP_VWSGRPOLIZAAUTO TO RAP_Garantias
GRANT SELECT, INSERT, UPDATE ON dbo.TMP_SAP_SGRPOLIZAOTRO TO RAP_Garantias
GRANT SELECT, INSERT, UPDATE ON dbo.TMP_SAP_SGRPOLIZAPATRIMONIAL TO RAP_Garantias
GRANT SELECT, INSERT, UPDATE ON dbo.TMP_SAP_VWSGRCONTRATOCREDITO TO RAP_Garantias
GRANT SELECT, INSERT, UPDATE ON dbo.TMP_SAP_VWSGRCREDITOBANCARIO TO RAP_Garantias
GRANT SELECT, INSERT, UPDATE ON dbo.TMP_GIROS_CONTRATOS TO RAP_Garantias
GRANT SELECT, INSERT, UPDATE ON dbo.GAR_COBERTURAS TO RAP_Garantias
GRANT SELECT, INSERT, UPDATE ON dbo.GAR_COBERTURAS_POLIZAS TO RAP_Garantias
GRANT SELECT, INSERT, UPDATE ON dbo.TMP_SAP_COBERTURAS_POLIZAS TO RAP_Garantias
GRANT SELECT, INSERT, UPDATE ON dbo.TMP_SAP_SGRCOBERTURAS TO RAP_Garantias
GRANT SELECT, INSERT, UPDATE ON dbo.TMP_SAP_SGRTIPOS_POLIZA TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SAP_VWSGRPOLIZA_HST TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SAP_VWSGRPOLIZACREDITOBANCARIO_HST TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SAP_VWSGRPOLIZACONTRATOCREDITO_HST TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SAP_POLIZASEXTERNAS_HST TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SAP_VWSGRPOLIZAAUTO_HST TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SAP_SGRPOLIZAOTRO_HST TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SAP_SGRPOLIZAPATRIMONIAL_HST TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SAP_VWSGRCONTRATOCREDITO_HST TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SAP_VWSGRCREDITOBANCARIO_HST TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.POLIZAS_HST TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON SICAD_CARTAS_CREDITO TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON SICAD_CC_IMPORTACION TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON SICAD_CC_IMPORTACION_POLIZAS TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON SICAD_FACTURAS_CEDIDAS TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON SICAD_FIDEICOMISO TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON SICAD_FIDUCIARIAS TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON SICAD_FISO_FIDEICOMETIDO TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON SICAD_FISO_FIDO_GRAVAMEN TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON SICAD_GAROPER TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON SICAD_GAROPER_FIDEICOMETIDO TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON SICAD_GAROPER_FIDO_GRAVAMEN TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON SICAD_GAROPER_GRAVAMEN TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON SICAD_GAROPER_LISTA TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON SICAD_GAROPER_PRIORIDAD TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON SICAD_REALES TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON SICAD_REALES_POLIZA TO RAP_Garantias
GRANT SELECT, INSERT, DELETE, UPDATE ON SICAD_VALORES TO RAP_Garantias
