GRANT EXECUTE ON dbo.pa_ActualizarRegistros TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_Alertas_Indicador_Inscripcion_Garantias_Reales TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_AsignarGarantiaGiro TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_CargarContratosVencidos TO RAP_Garantias
--GRANT EXECUTE ON dbo.pa_CDG_ConsultarGarantiasFiduciarias TO RAP_Garantias
--GRANT EXECUTE ON dbo.pa_CDG_ConsultarGarantiasReales TO RAP_Garantias
--GRANT EXECUTE ON dbo.pa_CDG_ConsultarGarantiasXOperacion TO RAP_Garantias
--GRANT EXECUTE ON dbo.pa_CDG_ConsultarGarantiasXValor TO RAP_Garantias
--GRANT EXECUTE ON dbo.pa_CDG_ConsultarOperaciones TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_Consulta_Info_Garantia_Eliminar TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_Consultar_Garantias_x_Perfil TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_ConsultarAvanceOperacionXOficina TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_ConsultarAvanceXOficina TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_ConsultarDetalleAvanceXGarantia TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_ConsultarDetalleAvanceXOperacion TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_EliminarBinTarjeta TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_EliminarGarantiaFiduciaria TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_EliminarGarantiaFiduciariaTarjeta TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_EliminarGarantiaReal TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_EliminarGarantiaValor TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_GarantiasXContrato TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_GarantiasXOperacion TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_GenerarGarantiasFiduciariasInfoCompleta TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_GenerarGarantiasRealesInfoCompleta TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_GenerarGarantiasValorInfoCompleta TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_GenerarInfoContratos TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_GenerarInfoDeudores TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_GenerarInfoGarantiasFiduciarias TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_GenerarInfoGarantiasFiduciariasContratos TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_GenerarInfoGarantiasReales TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_GenerarInfoGarantiasRealesAutomatico TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_GenerarInfoGarantiasRealesContratos TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_GenerarInfoGarantiasValor TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_GenerarInfoGarantiasValorContratos TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_GenerarInfoGaraReales TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_GenerarInfoGiros TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_Inconsistencias_Indicador_Inscripcion_Garantias_Reales TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_Inconsistencias_Indicador_Inscripcion_Garantias_Valor TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_Inconsistencias_Partido_Finca TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_InsertarBinTarjeta TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_InsertarBitacora TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_InsertarGarantiaFiduciaria TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_InsertarGarantiaFiduciariaTarjeta TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_InsertarGarantiaReal TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_InsertarGarantiaValor TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_InsertarValuacionReal TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_migrar_garantias TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_Modificar_Tipo_Garantia_Tarjeta TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_ModificarEstadoTarjeta TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_ModificarGarantiaFiduciaria TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_ModificarGarantiaFiduciariaTarjeta TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_ModificarGarantiaReal TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_ModificarGarantiaRealXML TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_ModificarGarantiaValor TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_ModificarValuacionReal TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_Obtener_Valuaciones_Reales TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_ObtenerCatalogos TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_ObtenerConsecutivoOperacion TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_ObtenerGarantiasFiduciariasContratos TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_ObtenerGarantiasFiduciariasOperaciones TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_ObtenerGarantiasFiduciariasXTarjeta TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_ObtenerGarantiasRealesContratos TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_ObtenerGarantiasRealesOperaciones TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_ObtenerGarantiasValorContratos TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_ObtenerGarantiasValorOperaciones TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_ObtenerNombreCliente TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_RegistroEjecucionProceso TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_Rpt_Avance_Contrato_X_Oficina_Cliente TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_Rpt_Avance_Operacion_X_Oficina_Cliente TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_Rpt_Avance_X_Oficina_Cliente TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_Rpt_Bitacora TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_Rpt_Contratos_Avance_X_Oficina_Cliente TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_Rpt_Contratos_Detalle_X_Garantia TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_Rpt_Detalle_X_Contrato TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_Rpt_Detalle_X_Garantia TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_Rpt_Detalle_X_Operacion TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_Rpt_Indicadores_X_Operacion TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_Rpt_Sumatoria_Montos_X_Operacion TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_ValidarOperaciones TO RAP_Garantias
GRANT EXECUTE ON dbo.Eliminar_Datos_Estructuras_SICC TO RAP_Garantias
GRANT EXECUTE ON dbo.Migrar_Garantias_Sicc TO RAP_Garantias
GRANT EXECUTE ON dbo.Actualizar_Registros_Garantias_Sicc TO RAP_Garantias
GRANT EXECUTE ON dbo.Cargar_Contratos_Vencidos_Sicc TO RAP_Garantias
GRANT EXECUTE ON dbo.Obtener_Resultado_Ejecucion_Procesos_Replica TO RAP_Garantias
GRANT EXECUTE ON dbo.Replicar_Valuaciones_Reales_Sicc TO RAP_Garantias
GRANT EXECUTE ON dbo.Replicar_Datos_Garantias_Reales_Sicc TO RAP_Garantias
GRANT EXECUTE ON dbo.Inconsistencias_Valuaciones_Garantia_Real TO RAP_Garantias
GRANT EXECUTE ON dbo.Insertar_Tipo_Bien_Relacionado TO RAP_Garantias
GRANT EXECUTE ON dbo.Consultar_Tipo_Bien_Relacionado TO RAP_Garantias
GRANT EXECUTE ON dbo.Consultar_Tipo_Poliza_Sugef TO RAP_Garantias
GRANT EXECUTE ON dbo.Eliminar_Tipo_Poliza_Sugef TO RAP_Garantias
GRANT EXECUTE ON dbo.Modificar_Tipo_Poliza_Sugef TO RAP_Garantias
GRANT EXECUTE ON dbo.Insertar_Tipo_Poliza_Sugef TO RAP_Garantias
GRANT EXECUTE ON dbo.Procesar_Polizas_Migradas TO RAP_Garantias
GRANT EXECUTE ON dbo.Modificar_Tipo_Bien_Relacionado TO RAP_Garantias
GRANT EXECUTE ON dbo.Eliminar_Tipo_Bien_Relacionado TO RAP_Garantias
GRANT EXECUTE ON dbo.Inconsistencias_Polizas_Garantias_Reales TO RAP_Garantias
GRANT EXECUTE ON dbo.Consultar_Garantia_Valor TO RAP_Garantias
GRANT EXECUTE ON dbo.Obtener_Garantias_Bitacora TO RAP_Garantias
GRANT EXECUTE ON dbo.Obtener_Datos_Garantia_Real_A_Normalizar TO RAP_Garantias
GRANT EXECUTE ON dbo.Generar_Informacion_Cambios_Garantias TO RAP_Garantias
GRANT EXECUTE ON dbo.Consultar_Cambios_Garantias TO RAP_Garantias
GRANT EXECUTE ON dbo.Inconsistencias_Porcentaje_Aceptacion_Real TO RAP_Garantias
GRANT EXECUTE ON dbo.Consultar_Historico_Porcentaje_Aceptacion TO RAP_Garantias
GRANT EXECUTE ON dbo.Insertar_Historico_Porcentaje_Aceptacion TO RAP_Garantias
GRANT EXECUTE ON dbo.Consultar_Porcentaje_Aceptacion TO RAP_Reportes
GRANT EXECUTE ON dbo.Eliminar_Porcentaje_Aceptacion TO RAP_Garantias
GRANT EXECUTE ON dbo.Modificar_Porcentaje_Aceptacion TO RAP_Garantias
GRANT EXECUTE ON dbo.Insertar_Porcentaje_Aceptacion TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_Rpt_Bitacora TO RAP_Garantias
GRANT EXECUTE ON dbo.pa_Rpt_Bitacora TO RAP_Reportes

