//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace Negocios.ActDirectory {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ActiveDirectorySoap", Namespace="http://tempuri.org/bcr.servicios.web/ActiveDirectory")]
    public partial class ActiveDirectory : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AutenticarOperationCompleted;
        
        private System.Threading.SendOrPostCallback TraerGruposOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExisteUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExisteGrupoOperationCompleted;
        
        private System.Threading.SendOrPostCallback TraerDatosUsuarioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ActiveDirectory() {
            this.Url = global::Negocios.Properties.Settings.Default.Negocios_ActDirectory_ActiveDirectory;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AutenticarCompletedEventHandler AutenticarCompleted;
        
        /// <remarks/>
        public event TraerGruposCompletedEventHandler TraerGruposCompleted;
        
        /// <remarks/>
        public event ExisteUsuarioCompletedEventHandler ExisteUsuarioCompleted;
        
        /// <remarks/>
        public event ExisteGrupoCompletedEventHandler ExisteGrupoCompleted;
        
        /// <remarks/>
        public event TraerDatosUsuarioCompletedEventHandler TraerDatosUsuarioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/bcr.servicios.web/ActiveDirectory/Autenticar", RequestNamespace="http://tempuri.org/bcr.servicios.web/ActiveDirectory", ResponseNamespace="http://tempuri.org/bcr.servicios.web/ActiveDirectory", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Autenticar(string codigoUsuario, string contrasena) {
            object[] results = this.Invoke("Autenticar", new object[] {
                        codigoUsuario,
                        contrasena});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AutenticarAsync(string codigoUsuario, string contrasena) {
            this.AutenticarAsync(codigoUsuario, contrasena, null);
        }
        
        /// <remarks/>
        public void AutenticarAsync(string codigoUsuario, string contrasena, object userState) {
            if ((this.AutenticarOperationCompleted == null)) {
                this.AutenticarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAutenticarOperationCompleted);
            }
            this.InvokeAsync("Autenticar", new object[] {
                        codigoUsuario,
                        contrasena}, this.AutenticarOperationCompleted, userState);
        }
        
        private void OnAutenticarOperationCompleted(object arg) {
            if ((this.AutenticarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AutenticarCompleted(this, new AutenticarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/bcr.servicios.web/ActiveDirectory/TraerGrupos", RequestNamespace="http://tempuri.org/bcr.servicios.web/ActiveDirectory", ResponseNamespace="http://tempuri.org/bcr.servicios.web/ActiveDirectory", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TraerGrupos(string codigoUsuario, string contrasena) {
            object[] results = this.Invoke("TraerGrupos", new object[] {
                        codigoUsuario,
                        contrasena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TraerGruposAsync(string codigoUsuario, string contrasena) {
            this.TraerGruposAsync(codigoUsuario, contrasena, null);
        }
        
        /// <remarks/>
        public void TraerGruposAsync(string codigoUsuario, string contrasena, object userState) {
            if ((this.TraerGruposOperationCompleted == null)) {
                this.TraerGruposOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTraerGruposOperationCompleted);
            }
            this.InvokeAsync("TraerGrupos", new object[] {
                        codigoUsuario,
                        contrasena}, this.TraerGruposOperationCompleted, userState);
        }
        
        private void OnTraerGruposOperationCompleted(object arg) {
            if ((this.TraerGruposCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TraerGruposCompleted(this, new TraerGruposCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/bcr.servicios.web/ActiveDirectory/ExisteUsuario", RequestNamespace="http://tempuri.org/bcr.servicios.web/ActiveDirectory", ResponseNamespace="http://tempuri.org/bcr.servicios.web/ActiveDirectory", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ExisteUsuario(string codigoUsuario) {
            object[] results = this.Invoke("ExisteUsuario", new object[] {
                        codigoUsuario});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ExisteUsuarioAsync(string codigoUsuario) {
            this.ExisteUsuarioAsync(codigoUsuario, null);
        }
        
        /// <remarks/>
        public void ExisteUsuarioAsync(string codigoUsuario, object userState) {
            if ((this.ExisteUsuarioOperationCompleted == null)) {
                this.ExisteUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExisteUsuarioOperationCompleted);
            }
            this.InvokeAsync("ExisteUsuario", new object[] {
                        codigoUsuario}, this.ExisteUsuarioOperationCompleted, userState);
        }
        
        private void OnExisteUsuarioOperationCompleted(object arg) {
            if ((this.ExisteUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExisteUsuarioCompleted(this, new ExisteUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/bcr.servicios.web/ActiveDirectory/ExisteGrupo", RequestNamespace="http://tempuri.org/bcr.servicios.web/ActiveDirectory", ResponseNamespace="http://tempuri.org/bcr.servicios.web/ActiveDirectory", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ExisteGrupo(string grupo) {
            object[] results = this.Invoke("ExisteGrupo", new object[] {
                        grupo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ExisteGrupoAsync(string grupo) {
            this.ExisteGrupoAsync(grupo, null);
        }
        
        /// <remarks/>
        public void ExisteGrupoAsync(string grupo, object userState) {
            if ((this.ExisteGrupoOperationCompleted == null)) {
                this.ExisteGrupoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExisteGrupoOperationCompleted);
            }
            this.InvokeAsync("ExisteGrupo", new object[] {
                        grupo}, this.ExisteGrupoOperationCompleted, userState);
        }
        
        private void OnExisteGrupoOperationCompleted(object arg) {
            if ((this.ExisteGrupoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExisteGrupoCompleted(this, new ExisteGrupoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/bcr.servicios.web/ActiveDirectory/TraerDatosUsuario", RequestNamespace="http://tempuri.org/bcr.servicios.web/ActiveDirectory", ResponseNamespace="http://tempuri.org/bcr.servicios.web/ActiveDirectory", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Usuario TraerDatosUsuario(string codigoUsuario) {
            object[] results = this.Invoke("TraerDatosUsuario", new object[] {
                        codigoUsuario});
            return ((Usuario)(results[0]));
        }
        
        /// <remarks/>
        public void TraerDatosUsuarioAsync(string codigoUsuario) {
            this.TraerDatosUsuarioAsync(codigoUsuario, null);
        }
        
        /// <remarks/>
        public void TraerDatosUsuarioAsync(string codigoUsuario, object userState) {
            if ((this.TraerDatosUsuarioOperationCompleted == null)) {
                this.TraerDatosUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTraerDatosUsuarioOperationCompleted);
            }
            this.InvokeAsync("TraerDatosUsuario", new object[] {
                        codigoUsuario}, this.TraerDatosUsuarioOperationCompleted, userState);
        }
        
        private void OnTraerDatosUsuarioOperationCompleted(object arg) {
            if ((this.TraerDatosUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TraerDatosUsuarioCompleted(this, new TraerDatosUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/bcr.servicios.web/ActiveDirectory")]
    public partial class Usuario {
        
        private string idField;
        
        private string userNameField;
        
        private string displayNameField;
        
        private string descriptionField;
        
        private string emailField;
        
        private string officeNameField;
        
        private string telephoneNumberField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string OfficeName {
            get {
                return this.officeNameField;
            }
            set {
                this.officeNameField = value;
            }
        }
        
        /// <remarks/>
        public string TelephoneNumber {
            get {
                return this.telephoneNumberField;
            }
            set {
                this.telephoneNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void AutenticarCompletedEventHandler(object sender, AutenticarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AutenticarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AutenticarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void TraerGruposCompletedEventHandler(object sender, TraerGruposCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TraerGruposCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TraerGruposCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ExisteUsuarioCompletedEventHandler(object sender, ExisteUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExisteUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExisteUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ExisteGrupoCompletedEventHandler(object sender, ExisteGrupoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExisteGrupoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExisteGrupoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void TraerDatosUsuarioCompletedEventHandler(object sender, TraerDatosUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TraerDatosUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TraerDatosUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591