<%@ Page Language="C#" MasterPageFile="~/Pagina Maestra/mtpMenuPrincipal.master"
    AutoEventWireup="true" CodeFile="frmGarantiasporPerfil.aspx.cs" Inherits="BCRGARANTIAS.Forms.frmGarantiasporPerfil"
    Title="BCR GARANTIAS - Garantías Por Perfil" %>

<%@ Register Assembly="System.Web.Extensions, Version=1.0.61025.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
    Namespace="System.Web.UI" TagPrefix="asp" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="ajaxToolkit" %>
<asp:Content ID="Content1" ContentPlaceHolderID="cphPrincipal" runat="Server">
    <asp:ScriptManager id="ScriptManager1" runat="server" EnablePageMethods="true">
    </asp:ScriptManager>
    <asp:UpdatePanel id="UpdatePanel1" runat="server">
        <contenttemplate>
<DIV><TABLE style="WIDTH: 775px" cellSpacing=1 cellPadding=1 width=775 align=center bgColor=window border=0><TBODY><TR><TD style="HEIGHT: 43px" align=center><!--TITULO PRINCIPAL--><CENTER><B><asp:label id="lblTitulo" runat="server" CssClass="TextoTitulo">Mantenimiento de Garantías Por Perfil</asp:label> </B></CENTER><B></B><!--<asp:label id="lblTexto" runat="server" CssClass="TextoTitulo"> Mantenimiento de Garantías Fiduciarias</asp:label>--></TD></TR><TR><TD vAlign=top><TABLE class="table_Default" borderColor=#005a9c width="60%" align=center border=2><!--SUBTITULO DE FORMULARIO--><TBODY><TR><TD class="TextoTitulo_2" width="100%" bgColor=#dcdcdc rowSpan=1>Información de la Operación </TD></TR><TR><TD><TABLE width="100%" align=center border=0><TBODY><TR><TD align=center colSpan=11><asp:label id="lblMensaje" runat="server" CssClass="TextoError">
</asp:label>&nbsp; </TD></TR><TR><TD class="td_Texto" width="24%"><asp:label id="lblTarjeta" runat="server">Tarjeta:</asp:label> </TD><TD class="td_TextoIzq" width="26%" colSpan=4><asp:textbox id="txtTarjeta" tabIndex=6 runat="server" BackColor="AntiqueWhite" Width="143px" MaxLength="16"></asp:textbox> </TD><TD class="td_TextoIzq" width="50%" colSpan=6><asp:button id="btnValidarTarjeta" tabIndex=7 runat="server" ToolTip="Verifica que la tarjeta sea valida en SISTAR" Text="Validar Tarjeta en SISTAR"></asp:button> </TD></TR><TR><TD class="td_Texto" width="24%"><asp:label id="lblDeudor" runat="server" ForeColor="SteelBlue" Font-Italic="true" Font-Bold="true" Visible="False">Deudor:</asp:label> </TD><TD class="td_TextoIzq" width="76%" colSpan=10><asp:label id="lblNombreDeudor" runat="server" ForeColor="SteelBlue" Font-Italic="true" Font-Bold="true" Visible="False"></asp:label> </TD></TR></TBODY></TABLE></TD></TR><TR><TD class="TextoTitulo_2" width="100%" bgColor=#dcdcdc rowSpan=1>Información&nbsp;de&nbsp;la Garantía por Perfil&nbsp;</TD></TR><TR><TD><TABLE width="100%" align=center border=0><TBODY><TR><TD align=center colSpan=4><asp:label id="lblMensaje3" runat="server" CssClass="TextoError"></asp:label>&nbsp; </TD></TR><TR><TD style="HEIGHT: 18px" class="td_Texto">Tipo de Garantía por Perfil:</TD><TD style="HEIGHT: 18px"><asp:dropdownlist id="ddlTipoGarantiaPorPerfil" tabIndex=8 runat="server" BackColor="AliceBlue" Width="513px" EnableViewState="True" Enabled="False"></asp:dropdownlist> </TD><TD style="HEIGHT: 18px" class="td_Texto"></TD><TD style="HEIGHT: 18px">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </TD></TR><TR><TD style="HEIGHT: 51px" class="td_Texto" vAlign=top>Observaciones:</TD><TD style="HEIGHT: 51px" colSpan=3><asp:textbox id="txtObservaciones" tabIndex=11 runat="server" BackColor="AliceBlue" CssClass="Txt_Style_Default" Width="508px" MaxLength="250" ToolTip="Nombre del Fiador" Enabled="False" Height="47px" TextMode="MultiLine" __designer:wfdid="w1"></asp:textbox></TD></TR><TR><TD></TD><TD colSpan=3></TD></TR><TR><TD align=right colSpan=4>&nbsp;<asp:button id="btnLimpiar" tabIndex=23 runat="server" ToolTip="Limpiar" Text="Limpiar" __designer:wfdid="w2"></asp:button><asp:button id="btnEliminar" tabIndex=25 runat="server" ToolTip="Eliminar Garantía" Text="Eliminar" Visible="False" __designer:wfdid="w3"></asp:button><asp:button id="btnModificar" tabIndex=25 runat="server" ToolTip="Modificar Garantía" Text="Modificar" __designer:wfdid="w4"></asp:button>&nbsp;&nbsp;&nbsp; </TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE><!--DEFINE BOTONERA--><TABLE style="WIDTH: 775px; HEIGHT: 19px" class="table_Default" width=775 align=center bgColor=window border=0><TBODY><TR><TD style="FONT-SIZE: 10px; COLOR: gray; FONT-FAMILY: Arial, Verdana, Tahoma" align=center>Banco de Costa Rica © Derechos reservados 2006.</TD></TR></TBODY></TABLE></DIV>
</contenttemplate>
    </asp:UpdatePanel>
</asp:Content>
